### ISSUE TITLE
URL is not defined?

### ISSUE THREAD

**Issue by pablogrs** [xymopen/proxy-multi-registries#2]
Hi guys, brilliant idea to solve what many struggle with.

Somehow I am falling in a error that I don't know how to fix. Would you know if there is a quick solution for it please?

```
root@4b9a4e27d6c1:~/support# npx github:xymopen/proxy-multi-registries --registries "https://registry.npmjs.org/" --address "localhost" --port 3500 
npx: installed 30 in 26.452s
Options:
  --help, -h        show help                                          [boolean]
  --version, -v     show version number                                [boolean]
  --address, -a     the address to bind to       [string] [default: "localhost"]
  --port, -p        the port to listen on              [number] [default: 22000]
  --registries, -r  the backend registries                    [array] [required]
  --default, -d     the registry used other than fetching packages      [string]

URL is not defined
```

**Comment by xymopen** [comment]
Glad it helped. Would you like to check your `node` version? The script relies on the WHATWG URL API which according to [Node.js Docs](https://nodejs.org/api/url.html#url_the_whatwg_url_api) is added after v6.13.0.

**Comment by xymopen** [comment]
Turns out that I missed some `require()` in files, making it require v10.0.0, in which `URL` is globally available.
I have added those missing `require()`s. Check it out and leave a comment if it helps.

**Comment by pablogrs** [comment]
Hi, thanks for your reply!
I only got the chance to try it out today only, I upgraded npm and node but now I am falling into another issue.

When running in Alpine I get 
```
/ # npx github:xymopen/proxy-multi-registries -r "https://registry.npmjs.org"
npx: installed 31 in 8.931s
YError: Invalid second argument. Expected function or boolean or object but received undefined.
    at argumentTypeError (/root/.npm/_npx/1573/lib/node_modules/proxy-multi-registries/node_modules/yargs/build/lib/argsert.js:64:11)
    at /root/.npm/_npx/1573/lib/node_modules/proxy-multi-registries/node_modules/yargs/build/lib/argsert.js:45:17
    at Array.forEach (<anonymous>)
    at Object.argsert (/root/.npm/_npx/1573/lib/node_modules/proxy-multi-registries/node_modules/yargs/build/lib/argsert.js:38:25)
    at Object.parse (/root/.npm/_npx/1573/lib/node_modules/proxy-multi-registries/node_modules/yargs/build/lib/yargs.js:555:19)
    at Object.<anonymous> (/root/.npm/_npx/1573/lib/node_modules/proxy-multi-registries/bin/server.js:161:4)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

```

```
/ # npm --version
6.14.4
/ # node --version
v12.17.0
```

I will try with Debian, but I found this weird
https://github.com/xymopen/proxy-multi-registries/blob/master/bin/server.js#L161
Sending undefined, exactly what yargs is complaining about

**Comment by xymopen** [comment]
Hmm, I was following Typescript instructions. Maybe there was bug in type definition for yargs. Will look into that.

**Comment by xymopen** [comment]
Turns out the second parameter of yargs `parse()` can be a `context` of type `object` and in Typescript `object` means `any` thus it failed to recognize `parseCallback()`. It should be fixed now.

**Comment by pablogrs** [comment]
That fix is working, thank you

I was finding an issue when using it with Docker, but using it locally I get something different.
Curl sort of works, I see the request on the server
```
curl http://localhost:22000/    
{"location":"https://registry.npmjs.org/"}
```
logs from the server:
```
Redirect http://localhost:22000/ to registry.npmjs.org
```

npm is also working properly, thank you!
