### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by AllanOricil** [xymopen/proxy-multi-registries#3]
I tried the command to setup multiple registries and did not work. Then I tried passing the `-h`  flag and had the same problem. I think npx can't get the PATH on Windows 10. My colleague is using on linux without any problem.

![image](https://user-images.githubusercontent.com/55927613/87962461-26f68880-caaf-11ea-9ab9-bca379793a0f.png)

Node version
![image](https://user-images.githubusercontent.com/55927613/87962490-31b11d80-caaf-11ea-836f-ef3a64c260e8.png)

Could you help me?

**Comment by xymopen** [comment]
The bug results from [index.js#L358@npm/npx](https://github.com/npm/npx/blob/v10.2.2/index.js#L358) where `npx` tries to resolve the bin script by looking for `"$basedir/node" BINJS` while `npm` generates `"$basedir//usr/bin/node" BINJS` for this module. There is not much we can fix in this module. The bug seems to be tracking at npm/npx#5 .

**Comment by AllanOricil** [comment]
> The bug results from [index.js#L358@npm/npx](https://github.com/npm/npx/blob/v10.2.2/index.js#L358) where `npx` tries to resolve the bin script by looking for `"$basedir/node" BINJS` while `npm` generates `"$basedir//usr/bin/node" BINJS` for this module. There is not much we can fix in this module. The bug seems to be tracking at [npm/npx#5](https://github.com/npm/npx/issues/5) .

Can you turn it in a package for me to install it globaly and then run like? Would that solve the problem somehow? 

`npm-multiproxy --args`

**Comment by AllanOricil** [comment]
Also, can you turn it in a package for me to install it globaly and then run it like?

npm-multiregistries --args

**Comment by AllanOricil** [comment]
> The bug results from [index.js#L358@npm/npx](https://github.com/npm/npx/blob/v10.2.2/index.js#L358) where `npx` tries to resolve the bin script by looking for `"$basedir/node" BINJS` while `npm` generates `"$basedir//usr/bin/node" BINJS` for this module. There is not much we can fix in this module. The bug seems to be tracking at [npm/npx#5](https://github.com/npm/npx/issues/5) .

I understood it now. Thanks anyway. Hope it gets fixed.
